var searchData=
[
  ['ohci_5fhost_5fdata_5ft',['OHCI_HOST_DATA_T',['../struct_o_h_c_i___h_o_s_t___d_a_t_a___t.html',1,'']]],
  ['os_5fflag_5fgrp',['os_flag_grp',['../structos__flag__grp.html',1,'']]],
  ['os_5fmem',['os_mem',['../structos__mem.html',1,'']]],
  ['os_5fmsg',['os_msg',['../structos__msg.html',1,'']]],
  ['os_5fmsg_5fpool',['os_msg_pool',['../structos__msg__pool.html',1,'']]],
  ['os_5fmsg_5fq',['os_msg_q',['../structos__msg__q.html',1,'']]],
  ['os_5fmutex',['os_mutex',['../structos__mutex.html',1,'']]],
  ['os_5fpend_5fdata',['os_pend_data',['../structos__pend__data.html',1,'']]],
  ['os_5fpend_5flist',['os_pend_list',['../structos__pend__list.html',1,'']]],
  ['os_5fpend_5fobj',['os_pend_obj',['../structos__pend__obj.html',1,'']]],
  ['os_5fq',['os_q',['../structos__q.html',1,'']]],
  ['os_5frdy_5flist',['os_rdy_list',['../structos__rdy__list.html',1,'']]],
  ['os_5fsem',['os_sem',['../structos__sem.html',1,'']]],
  ['os_5ftcb',['os_tcb',['../structos__tcb.html',1,'']]],
  ['os_5ftick_5fspoke',['os_tick_spoke',['../structos__tick__spoke.html',1,'']]],
  ['os_5ftmr',['os_tmr',['../structos__tmr.html',1,'']]],
  ['os_5ftmr_5fspoke',['os_tmr_spoke',['../structos__tmr__spoke.html',1,'']]]
];
