var searchData=
[
  ['rom_20stack_20support',['ROM stack support',['../group___audio___input___device___r_o_m___based.html',1,'']]],
  ['rom_20based_20class_20audio',['ROM based class audio',['../group___audio___input___device___r_o_m___based___audio___device___class.html',1,'']]],
  ['rom_20based_20core',['ROM based core',['../group___audio___input___device___r_o_m___based___core.html',1,'']]],
  ['rom_20stack_20support',['ROM stack support',['../group___audio___output___device___r_o_m___based.html',1,'']]],
  ['rom_20based_20core',['ROM based core',['../group___audio___output_device___r_o_m___based___core.html',1,'']]],
  ['ritimer_20example',['RITimer example',['../group___e_x_a_m_p_l_e_s___p_e_r_i_p_h__18_x_x43_x_x___r_i_t.html',1,'']]],
  ['rom_20stack_20support',['ROM stack support',['../group___generic___h_i_d___device___r_o_m___based.html',1,'']]],
  ['rom_20based_20core',['ROM based core',['../group___generic___h_i_d___device___r_o_m___based___core.html',1,'']]],
  ['rom_20based_20class_20hid',['ROM based class HID',['../group___generic___h_i_d___device___r_o_m___based___h_i_d___device___class.html',1,'']]],
  ['read_2fwrite_20of_20primitive_20data_20types',['Read/Write of Primitive Data Types',['../group___group___endpoint_primitive_r_w.html',1,'']]],
  ['read_2fwrite_20of_20primitive_20data_20types_20_28lpc11uxx_2c_20lpc1347_29',['Read/Write of Primitive Data Types (LPC11Uxx, LPC1347)',['../group___group___endpoint_primitive_r_w___l_p_c11_uxx.html',1,'']]],
  ['read_2fwrite_20of_20primitive_20data_20types_20_28lpc17xx_29',['Read/Write of Primitive Data Types (LPC17xx)',['../group___group___endpoint_primitive_r_w___l_p_c17xx.html',1,'']]],
  ['read_2fwrite_20of_20primitive_20data_20types_20_28lpc18xx_29',['Read/Write of Primitive Data Types (LPC18xx)',['../group___group___endpoint_primitive_r_w___l_p_c18xx.html',1,'']]],
  ['read_2fwrite_20of_20multi_2dbyte_20streams',['Read/Write of Multi-Byte Streams',['../group___group___endpoint_stream_r_w.html',1,'']]],
  ['read_2fwrite_20of_20primitive_20data_20types',['Read/Write of Primitive Data Types',['../group___group___pipe_primitive_r_w.html',1,'']]],
  ['read_2fwrite_20of_20multi_2dbyte_20streams',['Read/Write of Multi-Byte Streams',['../group___group___pipe_stream_r_w.html',1,'']]],
  ['rndis_20_28networking_29_20class_20driver',['RNDIS (Networking) Class Driver',['../group___group___u_s_b_class_r_n_d_i_s.html',1,'']]],
  ['rndis_20class_20device_20mode_20driver',['RNDIS Class Device Mode Driver',['../group___group___u_s_b_class_r_n_d_i_s_device.html',1,'']]],
  ['rndis_20class_20host_20mode_20driver',['RNDIS Class Host Mode Driver',['../group___group___u_s_b_class_r_n_d_i_s_host.html',1,'']]],
  ['rom_20stack_20support',['ROM stack support',['../group___keyboard___device___r_o_m___based.html',1,'']]],
  ['rom_20based_20core',['ROM based core',['../group___keyboard___device___r_o_m___based___core.html',1,'']]],
  ['rom_20based_20class_20hid',['ROM based class HID',['../group___keyboard___h_i_d___device___r_o_m___based___h_i_d___device___class.html',1,'']]],
  ['rtos_20support_20code',['RTOS support code',['../group___l_p_c_o_p_e_n___r_t_o_s_e_s.html',1,'']]],
  ['rom_20stack_20support',['ROM stack support',['../group___mass___storage___device___r_o_m___based.html',1,'']]],
  ['rom_20based_20core',['ROM based core',['../group___mass___storage___device___r_o_m___based___core.html',1,'']]],
  ['rom_20based_20class_20mass_20storage',['ROM based class Mass Storage',['../group___mass___storage___device___r_o_m___based___mass___storage___device___class.html',1,'']]],
  ['rom_20stack_20support',['ROM stack support',['../group___mouse___device___r_o_m___based.html',1,'']]],
  ['rom_20based_20core',['ROM based core',['../group___mouse___device___r_o_m___based___core.html',1,'']]],
  ['rom_20based_20class_20hid',['ROM based class HID',['../group___mouse___h_i_d___device___r_o_m___based___h_i_d___device___class.html',1,'']]],
  ['rtos_3a_20freertos_20support_20code',['RTOS: FreeRTOS support code',['../group___r_t_o_s___free_r_t_o_s.html',1,'']]],
  ['rtos_3a_20uc_2fos_2diii_20support_20code',['RTOS: uC/OS-III support code',['../group___r_t_o_s___u_c_o_s_i_i_i.html',1,'']]],
  ['rom_20stack_20support',['ROM stack support',['../group___virtual___serial___device___r_o_m___based.html',1,'']]],
  ['rom_20based_20class_20cdc',['ROM based class CDC',['../group___virtual___serial___device___r_o_m___based___c_d_c___device___class.html',1,'']]],
  ['rom_20based_20core',['ROM based core',['../group___virtual___serial___device___r_o_m___based___core.html',1,'']]]
];
